project:
  type: book
  output-dir: docs

book:
  title: "Data visualisation with R"
  author: "Sophie Lee"
  date: 2024-09-04
  downloads: [pdf]  
  search: true
  navbar:
    right: 
      - icon: github
        href: https://github.com/sophie-a-lee/
        aria-label: Github
      - icon: cup-hot
        href: https://buymeacoffee.com/sophie_a_lee
        aria-label: Buy me a coffee
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_aes_geom.qmd
    - 03_scales.qmd
    - 04_annotation.qmd
    - 05_theme.qmd
    - 06_facet.qmd
  appendices: 
    - data_description.qmd
    - exercise_solutions.qmd

format:
  html:
    theme:
      light: [pulse, style.scss]
      dark: darkly
  pdf:
    documentclass: scrreprt